### Listar enderecos
GET http://localhost:3000/endereco

### Listar enderecos 
GET http://localhost:3000/endereco/1

###Criar endereco
POST http://localhost:3000/endereco
Content-Type: application/json

{
    "id_cliente": 2,
    "estado": "DF",
    "cidade": "Taguatinga",
    "bairro": "Taguatinga",
    "rua": "Pistão Sul",
    "complemento": "Não tem",
    "cep": "77777-777"
}

### Atualizar um endereco
PATCH http://localhost:3000/endereco/1
Content-Type: application/json

{
    "estado": "DF",
    "cidade": "Águas Claras",
    "bairro": "Bairro dos enzos",
    "rua": "Avenida das araucárias",
    "complemento": "Não tem"
}

### Deletar um endereco
DELETE http://localhost:3000/endereco/1