### list favorito
GET http://localhost:3000/favoritos

### get favorito
GET http://localhost:3000/favoritos/1

### create favorito
POST http://localhost:3000/favoritos
Content-Type: application/json

{ 
    "id_produto": 1,
    "id_cliente": 2,
    "data_adicao": "2025-06-10"
}

### update favorito
PATCH  http://localhost:3000/favoritos/1
Content-Type: application/json

{ 
    "id_produto": 1,
    "data_adicao": "2025-07-10"
}

### delete favorito
DELETE http://localhost:3000/favoritos/2